version: '3'

services:
  db:
    image: mariadb:10.4.12
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:rw
    env_file:
      - mariadb.env
      - db.env
    networks:
      - backend

  redis:
    image: redis:5.0.8-alpine
    restart: always
    networks:
      - backend

  app:
    image: nextcloud:18.0.3-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:rw
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.davidcharbonnier.local
    env_file:
      - nextcloud.env
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - backend

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-traefik"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.davidcharbonnier.local`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
    networks:
      - proxy-public
      - backend

  cron:
    image: nextcloud:18.0.3-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:rw
    entrypoint: /cron.sh
    depends_on:
      - app
    networks:
      - backend

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/nextcloud/db
      o: bind
  nextcloud:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/nextcloud/app
      o: bind

networks:
  backend:
  proxy-public:
    external:
      name: proxy-public
