version: '3'

services:
  db:
    image: mariadb:10.4.12
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:rw
    env_file:
      - mariadb.env
      - db.env
    networks:
      - backend

  redis:
    image: redis:5.0.8-alpine
    restart: always
    networks:
      - backend

  app:
    image: nextcloud:18.0.3-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:rw
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.davidcharbonnier.fr
    env_file:
      - nextcloud.env
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - backend

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.davidcharbonnier.fr
      - LETSENCRYPT_HOST=cloud.davidcharbonnier.fr
      - LETSENCRYPT_EMAIL=contact@davidcharbonnier.fr
    depends_on:
      - app
    networks:
      - frontend
      - backend

  cron:
    image: nextcloud:18.0.3-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:rw
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - backend

  proxy:
    build: ./proxy
    restart: always
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
      - conf:/etc/nginx/conf.d:rw
    networks:
      - frontend

  docker-gen:
    build: ./docker-gen
    command: -notify-sighup proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    container_name: docker-gen
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d:rw
      - conf:/etc/nginx/conf.d:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend
    depends_on:
      - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LETSENCRYPT_TEST=false
      - NGINX_PROXY_CONTAINER=proxy
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
    networks:
      - frontend
    depends_on:
      - proxy

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/nextcloud/db
      o: bind
  nextcloud:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/nextcloud/app
      o: bind
  certs:
  vhost:
  html:
  conf:

networks:
  backend:
  frontend:
